# .github/workflows/astro-check.yml
name: Astro Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  astro-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Deps
        run: npm install

      - name: Astro Check
        run: npx astro check
